/* P66-Tuner binary patch verifier
 * Reliability gate between patch generation (js/xdf-map.js) and the
 * patched-binary download. Every patch must prove, against the actual
 * bytes, that it is safe to flash:
 *
 *   P66.verifyPatches(catalog, binBytes, patchResult)
 *     -> { ok, checked, failures: [{ addressHex, check, message }],
 *          warnings: [{ addressHex, check, message }] }
 *
 * Failure checks (any one blocks the download):
 *   range       patch address range lies inside the binary image
 *   table       patch address range lies inside its table's XDF-defined region
 *   old-value   source binary actually holds patch.oldValue at the address
 *               (catches patches built against a different base binary)
 *   conflict    no two patches write the same byte
 *   read-back   the patched image reads back patch.newValue at the address
 *   value-range newValue fits in sizeBytes
 *
 * Warnings (reported, do not block):
 *   overlap     patch touches a known XDF overlap region (two definitions
 *               claim the same bytes — from catalog.audit.overlapRegions,
 *               or the built-in P66 V6 list when the deftitle matches)
 *
 * Depends on P66.findTable from js/xdf-map.js (load xdf-map.js first).
 * Works in browser and node.
 */
(function (global) {
  'use strict';

  var P66 = (global.P66 = global.P66 || {});

  function parseAddr(a) {
    if (typeof a === 'number') return a;
    var s = String(a || '').trim();
    return s.slice(0, 2).toLowerCase() === '0x' ? parseInt(s, 16) : parseInt(s, 10);
  }

  function hex(addr) {
    return '0x' + addr.toString(16).toUpperCase();
  }

  // Big-endian raw read, matching the 68HC11 convention in xdf-map.js.
  function readRaw(binBytes, address, sizeBytes) {
    if (sizeBytes === 2) return (binBytes[address] << 8) | binBytes[address + 1];
    return binBytes[address];
  }

  function tableByteRange(catalog, tableName) {
    var find = P66.findTable;
    if (typeof find !== 'function') return null;
    var t = find(catalog, tableName);
    if (!t || t.address === '' || t.address === undefined) return null;
    var rows = parseInt(t.rows, 10) || 1;
    var cols = parseInt(t.cols, 10) || 1;
    var bits = parseInt(t.elementSizeBits || '8', 10) || 8;
    var eb = bits === 16 ? 2 : 1;
    var base = parseAddr(t.address);
    if (!isFinite(base) || base < 0) return null;
    return { base: base, size: rows * cols * eb, title: t.title };
  }

  function rangesOverlap(aStart, aSize, bStart, bSize) {
    return aStart < bStart + bSize && bStart < aStart + aSize;
  }

  // Known XDF overlap regions for the P66 V6 3.4L XDF, generated by
  // tools/xdf-audit.js on 2026-10-08 (two definitions claim the same bytes).
  // Used as a fallback when the catalog carries no audit block — e.g. an XDF
  // uploaded in the browser and parsed on the fly. Only applied when the
  // catalog's deftitle matches, so a different XDF never gets stale regions.
  var KNOWN_DEFTITLE = '3.4L Rear Wheel Drive P66 V6';
  var DEFAULT_OVERLAPS = [
    { start: 0x4, size: 1, startHex: '0x4' },
    { start: 0x6, size: 3, startHex: '0x6' },
    { start: 0x5FB, size: 10, startHex: '0x5FB' },
    { start: 0x68D, size: 4, startHex: '0x68D' },
    { start: 0xB5D, size: 1, startHex: '0xB5D' },
    { start: 0xEA5, size: 1, startHex: '0xEA5' },
    { start: 0x8005, size: 1, startHex: '0x8005' },
    { start: 0x8009, size: 5, startHex: '0x8009' },
    { start: 0x81C5, size: 8, startHex: '0x81C5' },
    { start: 0x81DE, size: 3, startHex: '0x81DE' },
    { start: 0x869F, size: 2, startHex: '0x869F' },
    { start: 0x88F6, size: 1, startHex: '0x88F6' }
  ];

  function overlapRegionsFor(catalog) {
    if (catalog && catalog.audit && catalog.audit.overlapRegions) {
      return catalog.audit.overlapRegions;
    }
    if (catalog && catalog.deftitle === KNOWN_DEFTITLE) return DEFAULT_OVERLAPS;
    return [];
  }

  /**
   * Verify a patchResult ({ patches, patched, error }) from
   * P66.applyFuelSuggestions against the source binary and catalog.
   */
  function verifyPatches(catalog, binBytes, patchResult) {
    var failures = [];
    var warnings = [];
    var checked = 0;

    function fail(patch, check, message) {
      failures.push({
        address: patch ? patch.address : null,
        addressHex: patch ? (patch.addressHex || hex(patch.address)) : null,
        check: check,
        message: message
      });
    }
    function warn(patch, check, message) {
      warnings.push({
        addressHex: patch.addressHex || hex(patch.address),
        check: check,
        message: message
      });
    }

    if (!patchResult || patchResult.error) {
      fail(null, 'input', 'No patch result to verify' +
        (patchResult && patchResult.error ? ': ' + patchResult.error : '.'));
      return { ok: false, checked: 0, failures: failures, warnings: warnings };
    }
    var patches = patchResult.patches || [];
    var patched = patchResult.patched;
    if (!patched) {
      fail(null, 'input', 'Patch result has no patched image.');
      return { ok: false, checked: 0, failures: failures, warnings: warnings };
    }
    if (patched.length !== binBytes.length) {
      fail(null, 'input', 'Patched image length (' + patched.length +
        ') differs from source binary length (' + binBytes.length + ').');
    }

    var n = binBytes.length;
    var claimed = []; // byte ranges already written, for conflict detection
    var overlapRegions = overlapRegionsFor(catalog);

    patches.forEach(function (p) {
      checked++;
      var size = p.sizeBytes === 2 ? 2 : 1;
      var maxVal = size === 2 ? 0xFFFF : 0xFF;

      // 1. Address range inside the image.
      if (!(p.address >= 0) || !isFinite(p.address) || p.address + size > n) {
        fail(p, 'range', 'Address range ' + hex(p.address) + ' +' + size +
          ' is outside the ' + n + '-byte image.');
        return; // further checks are meaningless off-image
      }

      // 2. Address range inside the table's XDF-defined region.
      var region = tableByteRange(catalog, p.table);
      if (!region) {
        fail(p, 'table', 'Table "' + p.table + '" not found with a valid ' +
          'address/geometry in the XDF catalog.');
      } else if (p.address < region.base || p.address + size > region.base + region.size) {
        fail(p, 'table', hex(p.address) + ' +' + size + ' falls outside "' +
          region.title + '" XDF region ' + hex(region.base) + ' +' + region.size + '.');
      }

      // 3. Old value matches the source binary (guards against a wrong base bin).
      var actualOld = readRaw(binBytes, p.address, size);
      if (actualOld !== p.oldValue) {
        fail(p, 'old-value', 'Source binary holds ' + actualOld + ' at ' +
          (p.addressHex || hex(p.address)) + ' but the patch expects oldValue ' +
          p.oldValue + ' — wrong base binary?');
      }

      // 4. No two patches write the same byte.
      for (var i = 0; i < claimed.length; i++) {
        if (rangesOverlap(p.address, size, claimed[i].address, claimed[i].size)) {
          fail(p, 'conflict', (p.addressHex || hex(p.address)) +
            ' overlaps an earlier patch at ' +
            (claimed[i].addressHex || hex(claimed[i].address)) + '.');
          break;
        }
      }
      claimed.push({ address: p.address, size: size, addressHex: p.addressHex });

      // 5. New value fits the element size.
      if (!(p.newValue >= 0) || p.newValue > maxVal || Math.round(p.newValue) !== p.newValue) {
        fail(p, 'value-range', 'newValue ' + p.newValue + ' does not fit in ' +
          size + ' byte(s).');
      }

      // 6. Read-back: the patched image holds newValue at the address.
      if (patched.length === n) {
        var actualNew = readRaw(patched, p.address, size);
        if (actualNew !== p.newValue) {
          fail(p, 'read-back', 'Patched image reads back ' + actualNew + ' at ' +
            (p.addressHex || hex(p.address)) + ' but the patch wrote ' +
            p.newValue + '.');
        }
      }

      // 7. Overlap-region warning (informational only).
      for (var o = 0; o < overlapRegions.length; o++) {
        var r = overlapRegions[o];
        if (rangesOverlap(p.address, size, r.start, r.size)) {
          warn(p, 'overlap', (p.addressHex || hex(p.address)) + ' touches known ' +
            'XDF overlap region ' + r.startHex + ' +' + r.size +
            ' (two definitions claim these bytes) — confirm the right table owns it.');
          break;
        }
      }
    });

    return { ok: failures.length === 0, checked: checked, failures: failures, warnings: warnings };
  }

  P66.verifyPatches = verifyPatches;
})(typeof window !== 'undefined' ? window : global);
